-- Cron is intentionally not created in a migration because the project URL
-- and authorization token are deployment secrets. Configure these three jobs
-- after deployment using Supabase Dashboard > Integrations > Cron:
-- 1. flight-scanner every 12 hours
-- 2. analyze-price after the scanner
-- 3. alert-processor after price analysis
