-- Scheduling is intentionally not created in a migration because project
-- URLs and authorization tokens are deployment secrets. The source-backed
-- scan/analyze/feed sequence is owned by GitHub Actions workflow
-- `.github/workflows/fast-flights-pipeline.yml` and runs every 12 hours.
-- Configure alert delivery separately only after the internal function secret
-- and notification provider credentials are present.
